services:
  messages-front-nginx:
    container_name: messages-front-nginx
    image: messages-front-nginx-image:prod
    build:
      context: ..
      dockerfile: _docker/nginx/Dockerfile.prod
    networks:
      - sandbox-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.messages-front.rule=Host(`messages.rfess.fr`) && PathPrefix(`/`)"
      - "traefik.http.routers.messages-front.entrypoints=web"
      - "traefik.http.services.messages-front.loadbalancer.server.port=80"

networks:
  sandbox-network:
    external: true
