services:
  web:
    image: nginx:alpine
    container_name: messages-front-nginx
    volumes:
      - ../public:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - sandbox-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.messages-front.rule=Host(`messages.me`) && PathPrefix(`/`)"
      - "traefik.http.routers.projet5.entrypoints=web"
      - "traefik.http.services.projet5.loadbalancer.server.port=80"

networks:
  sandbox-network:
    external: true
